In [1]:
import pandas as pd

In [2]:
from BGN_LNG.Utils.utils_spark import *

ModuleNotFoundError: No module named 'BGN_LNG'

In [3]:
from xbbg import blp

ref = blp.bdp(tickers='COA Comdty', flds=['Security_Name', 'GICS_Sector_Name'])
ref

                      security_name
COA Comdty  BRENT CRUDE FUTR  Mar26

In [47]:
month_labels = ["F, G, H, J, K, M, N, Q, U V, X, Z"]
CO_tickers26 = []
bbb = blp.bdh(
    tickers='CO Comdty', flds=["px_settle", "volume", "time"],
    start_date='2026-01-12', end_date='2026-01-13',
)

In [38]:
aaa = blp.bdp(['TZTF7 Comdty', 'TZTG7 Comdty', 'TZTH7 Comdty'], flds=['Last_Price', "volume", "time"])

In [49]:
aaa

             last_price   volume        time
TZTF7 Comdty     29.783  42614.0  01/16/2026
TZTG7 Comdty       28.7   4530.0    09:43:29
TZTH7 Comdty       29.0  42309.0  01/16/2026

In [46]:
blp.bdh('FJSA Comdty',['PX_LAST','IVOL','VOLUME_TOTAL_CALL'],
        start_date='2026-01-12', end_date='2026-01-19',
                 IVOL_DELTA_LEVEL='DELTA_LVL_50',
                 IVOL_MATURITY='MATURITY_30D',
                 IVOL_DELTA_PUT_OR_CALL='IVOL_CALL')

           FJSA Comdty
               PX_LAST VOLUME_TOTAL_CALL
2026-01-12      30.246           47180.0
2026-01-13      31.473           44265.0
2026-01-14      31.813           43185.0
2026-01-15      33.158           36172.0
2026-01-16      36.879           46892.0
2026-01-19      33.935               NaN